set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

find_program(ZIG_EXECUTABLE zig REQUIRED)

set(CMAKE_C_COMPILER "${ZIG_EXECUTABLE}")
set(CMAKE_C_COMPILER_ARG1 cc)
set(CMAKE_CXX_COMPILER "${ZIG_EXECUTABLE}")
set(CMAKE_CXX_COMPILER_ARG1 c++)
set(CMAKE_AR "${CMAKE_CURRENT_LIST_DIR}/zig-ar.cmd")
set(CMAKE_RANLIB "${CMAKE_CURRENT_LIST_DIR}/zig-ranlib.cmd")

set(ZIG_WINDOWS_GNU_TARGET x86_64-windows-gnu)
set(CMAKE_C_COMPILER_TARGET ${ZIG_WINDOWS_GNU_TARGET})
set(CMAKE_CXX_COMPILER_TARGET ${ZIG_WINDOWS_GNU_TARGET})

set(CMAKE_C_FLAGS_INIT "-target ${ZIG_WINDOWS_GNU_TARGET}")
set(CMAKE_CXX_FLAGS_INIT "-target ${ZIG_WINDOWS_GNU_TARGET}")
set(CMAKE_EXE_LINKER_FLAGS_INIT "-target ${ZIG_WINDOWS_GNU_TARGET}")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "-target ${ZIG_WINDOWS_GNU_TARGET}")
set(CMAKE_MODULE_LINKER_FLAGS_INIT "-target ${ZIG_WINDOWS_GNU_TARGET}")

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
